# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-9I0KN8IHltJx_yb4GjTZTfjalwGaKFP
"""

def add_numbers(a, b):
    return a + b


result = add_numbers(5, 3)
print(result)

def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)


num = 5
print(f"Factorial of {num} is {factorial(num)}")

def is_prime(n):
    """Check if a number is prime."""
    if n < 2:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True


print(is_prime(7))
print(is_prime(10))

def generate_fibonacci(n):
    if n <= 0:
        return []
    elif n == 1:
        return [0]

    fib_sequence = [0, 1]
    for _ in range(2, n):
        fib_sequence.append(fib_sequence[-1] + fib_sequence[-2])

    return fib_sequence

N = 10
print(generate_fibonacci(N))

def find_largest(a, b, c):
    return max(a, b, c)


largest = find_largest(10, 25, 15)
print("The largest number is:", largest)

num = int(input("Enter a number: "))

if num % 2 == 0:
    print(f"{num} is an even number.")
else:
    print(f"{num} is an odd number.")

def is_palindrome(s):
    s = ''.join(c.lower() for c in s if c.isalnum())
    return s == s[::-1]

print(is_palindrome("racecar"))
print(is_palindrome("hello"))

def power (base,exponent):
    return base ** exponent

result1 = power(2,3)
result2 = power(5,2)
print(result1)
print(result2)

